[package]
name = "alloy-smoke"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.18", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
alloy-provider = { workspace = true, default-features = false, features = ["reqwest"] }
alloy-transport-http = { workspace = true }
alloy-primitives = { workspace = true }
alloy-network = { workspace = true }
tower = "0.5.2"
