[workspace]
members = [
    "bin/artemis",
    "bin/cli",
    "crates/artemis-core",
    "crates/generator",
    "crates/strategies/*",
    "examples/sandwich-bot",
    "crates/clients/*", 
    "examples/*",
]
exclude = [
    "crates/clients/chainbound",
]

default-members = ["bin/artemis", "bin/cli"]
resolver = "2"

[workspace.dependencies]
## eth
serde = { version = "1.0.205", features = ["derive"] }

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'

## note: remove alloy patches; rely on fiber compat

